// Icons grouped by what they are for.

export type Collection = { id: string; label: string; names: string[] }

export const COLLECTIONS: Collection[] = [
  {
    id: "objects",
    label: "Home & objects",
    names: [
      "home",
      "map",
      "map-pin",
      "pin",
      "calendar",
      "cart",
      "gear",
      "bulb",
      "lock",
      "lock-open",
      "key",
      "shield",
      "shield-check",
      "trash",
      "flask",
      "puzzle",
      "diamond",
      "cube",
      "gauge"
    ],
  },
  {
    id: "communication",
    label: "Communication",
    names: [
      "mail",
      "chat",
      "call",
      "phone",
      "megaphone",
      "bell",
      "share",
      "user",
      "users",
      "smile",
      "frown",
      "thumbs-up",
      "thumbs-down"
    ],
  },
  {
    id: "nature",
    label: "Weather & nature",
    names: [
      "leaf",
      "sun",
      "rain",
      "clouds",
      "flame",
      "fire",
      "bolt",
      "umbrella",
      "moon"
    ],
  },
  {
    id: "media",
    label: "Media & devices",
    names: [
      "camera",
      "videocam",
      "image",
      "mic",
      "gamepad",
      "monitor",
      "laptop",
      "tablet",
      "chip",
      "code",
      "browser",
      "globe"
    ],
  },
  {
    id: "interface",
    label: "Interface",
    names: [
      "plus",
      "minus",
      "x",
      "close",
      "check",
      "menu",
      "ellipsis",
      "ellipsis-vertical",
      "info",
      "circle-question-mark",
      "circle-alert",
      "warning",
      "ban",
      "eye",
      "eye-off",
      "search",
      "filter",
      "maximize",
      "minimize",
      "zoom-in",
      "zoom-out",
      "layout-grid",
      "list",
      "table",
      "star",
      "heart",
      "bookmark",
      "flag",
      "tag",
      "link",
      "circle",
      "play",
      "player"
    ],
  },
  {
    id: "files",
    label: "Files",
    names: [
      "file",
      "file-text",
      "file-plus",
      "file-check",
      "file-x",
      "files",
      "doc",
      "folder",
      "folder-open",
      "folder-plus",
      "archive",
      "inbox",
      "save",
      "copy",
      "clipboard",
      "clipboard-check",
      "clipboard-list",
      "list-checks",
      "paperclip",
      "receipt",
      "scroll",
      "sticky-note",
      "layers",
      "database",
      "news"
    ],
  },
  {
    id: "text",
    label: "Text & tools",
    names: [
      "type",
      "text-align-start",
      "text-align-center",
      "text-align-end",
      "bold",
      "italic",
      "underline",
      "quote",
      "hash",
      "at-sign",
      "signature",
      "pencil",
      "pen",
      "highlighter",
      "eraser",
      "ruler",
      "brush",
      "stamp",
      "scissors",
      "printer",
      "book",
      "book-open",
      "notebook",
      "library"
    ],
  },
  {
    id: "arrows",
    label: "Arrows",
    names: [
      "arrow-up",
      "arrow-down",
      "arrow-left",
      "arrow-right",
      "arrow-up-right",
      "chevron-up",
      "chevron-down",
      "chevron-left",
      "chevron-right",
      "undo",
      "redo",
      "refresh-cw",
      "upload",
      "download",
      "log-out",
      "external-link",
      "send"
    ],
  },
]
